# Generated by Django 3.1.7 on 2021-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
