# Generated by Django 3.1.7 on 2021-03-13 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestatus',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
