# Generated by Django 3.1.7 on 2021-03-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicestatus_date_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicestatus',
            old_name='status',
            new_name='paid',
        ),
    ]
