# Generated by Django 3.1.7 on 2021-03-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210313_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
