# Generated by Django 3.1.7 on 2021-03-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210313_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
