# Generated by Django 3.1.7 on 2021-03-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210311_2212'),
        ('bills', '0005_auto_20210320_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
